[WIP] 更新接口并重写example
last-lab/last pull request #114
Opened 2023-11-14 02:55 UTC by sys555

1. example 见 test_scheduler.py ;
2. 测试需求待讨论 ;

2023-11-15 04:54 UTC, sys555 commented
已完善 [test_scheduler 对回调函数进行测试]

2023-11-15 05:45 UTC, WangXuhongCN commented on last/query/.gitignore
这个文件删掉，无用文件

2023-11-15 05:45 UTC, WangXuhongCN commented on last/query/test_data.py
这个挪到test里

2023-11-15 05:45 UTC, WangXuhongCN requested changes
好好看一下test的写法

2023-11-15 05:56 UTC, sys555 commented
test_scheduler 已参考 其他test脚本更改

2023-11-16 06:27 UTC, WangXuhongCN requested changes
删除不需要的文件

2023-11-16 06:27 UTC, WangXuhongCN commented on last/client/call_llm.py
> +        output = output.content
output = output.content 这里不要这么改，换个中间变量的名字

2023-11-16 06:27 UTC, WangXuhongCN commented on last/llms/model/base_model.py
>  class HTTPAPILLMModel(BaseLLMModel):
最好保留两种模式，原来的模式也保留在代码里面，默认采用你的代码，如果有需求也可以用原来的代码

2023-11-16 07:09 UTC, sys555 commented
所有comment 均 修改

2023-11-16 07:25 UTC, WangXuhongCN approved these changes
LGTM

2023-11-17 05:55 UTC, WangXuhongCN approved these changes
LGTM

2023-11-17 05:55 UTC, merged