增加数据标注页面的抽象数据结构
last-lab/last pull request #15
Opened 2023-09-09 03:48 UTC by eveyuyi

* 添加了annotation数据格式定义：根据label-studio的annotation导出，定义本系统的annotation数据格式
* 添加了数据标注页面的抽象数据结构、输入输出

2023-09-09 09:12 UTC, WangXuhongCN requested changes
有些细节还需要完善一下，

2023-09-09 09:12 UTC, WangXuhongCN commented on last/types/annotation.py
> +class Annotations(BaseModel):
这个最好继承一下Record基类，然后之后我封装的方法可以被复用

2023-09-09 09:12 UTC, WangXuhongCN commented on last/types/labeldata.py
> +    def annotate(self):
可能要跟亮亮商议一下如何在这里调用label studio

2023-09-09 09:12 UTC, WangXuhongCN commented on last/types/labeldata.py
> +    def annotate(self):
也许可以封装一个labelstudio调用器，具体方法用pass

2023-09-09 09:12 UTC, WangXuhongCN commented on last/types/annotation.py
> +    start: Optional[int] = None  # 起始位置，可选
为啥这里全是Optional

2023-09-09 09:12 UTC, WangXuhongCN commented on last/types/labeldata.py
> +        pass
所有的方法要定义输入输出类型，

2023-09-12 00:46 UTC, eveyuyi commented on last/types/annotation.py
> +class Annotations(BaseModel):
已经添加。 annotation.py里面数据结构是按照label studio的json文件格式定义的

2023-09-12 00:48 UTC, eveyuyi commented on last/types/annotation.py
> +    start: Optional[int] = None  # 起始位置，可选
因为可能有不同的label方式，比如如果是select的标注方式，就没有start, end字段；如果是hightlight形式，就没有choices字段。所以全部写的optional😂

2023-09-12 02:25 UTC, eveyuyi commented on last/types/labeldata.py
> +        pass
添加啦

2023-09-12 06:43 UTC, WangXuhongCN commented on last/types/labeldata.py
> +        pass
输出的东西大概长什么样子，不能光写明是字典，key代表什么 value代表什么

2023-09-12 07:13 UTC, WanChengXue requested changes
修改一下所有类，变量的名称，统一规范

2023-09-12 07:13 UTC, WanChengXue commented on last/types/annotation.py
> +class _AnnotationValue(BaseModel):
类名不会有_开头

2023-09-12 07:13 UTC, WanChengXue commented on last/types/annotation.py
> +class _AnnotationResult(BaseModel):
类名不会用_开始

2023-09-12 07:13 UTC, WanChengXue commented on last/types/labeldata.py
> +    def annotate(self):
这个annotate应该作为后端的一个方法，不应该放在这里，最多就是前端返回annotate的结果到后端，后端调用这个annotate方法放到数据库里面。yuyi的工作不需要直接调用labelstudio

2023-09-12 07:13 UTC, WanChengXue commented on last/types/labeldata.py
> +
这个方法，_LabelData是啥，以及这个类是用来那里的，下面那个也是

2023-09-12 07:55 UTC, eveyuyi commented on last/types/annotation.py
> +class _AnnotationValue(BaseModel):
已修改

2023-09-12 07:56 UTC, eveyuyi commented on last/types/annotation.py
> +class _AnnotationResult(BaseModel):
已修改

2023-09-12 11:15 UTC, eveyuyi commented on last/types/labeldata.py
> +
已经修改

2023-09-12 11:17 UTC, WangXuhongCN approved these changes
LGTM

2023-09-12 11:18 UTC, eveyuyi commented on last/types/labeldata.py
> +        pass
已添加

2023-09-12 11:22 UTC, WanChengXue approved these changes

2023-09-12 11:24 UTC, merged