新增选择prompt类型选项
last-lab/last pull request #156
Opened 2023-12-14 12:58 UTC by sys555

1. 创建评测流程中新增选择prompt类型选项;
2. 调用外部脚本生成prompt;
3. 调用外部脚本解析 critic result;

2023-12-14 13:00 UTC, WangXuhongCN requested changes
需要进行修改：要不然就写自动拉取gitlab的操作，要不然就只放我们用到的脚本。一些没有用的脚本也许不需要放进来

2023-12-14 13:02 UTC, WangXuhongCN commented on last/types/prompt_template.py
> +    # p6.py 复制自 p7
这句注释啥意思

2023-12-14 13:05 UTC, sys555 commented on last/types/prompt_template.py
> +    # p6.py 复制自 p7
他们缺了个p6.py，这里暂时复制p7.py当作p6.py使用

2023-12-14 13:46 UTC, WangXuhongCN commented
要不先把不需要的文件先删除，只保留有用的

2023-12-15 04:08 UTC, WangXuhongCN approved these changes
LGTM

2023-12-15 04:09 UTC, merged