feat: 修改新建评测弹窗+新增方案详情弹窗+接口字段对齐
last-lab/last pull request #29
Opened 2023-09-14 07:18 UTC by Echo-minn

2023-09-14 08:38 UTC, WangXuhongCN requested changes
这个PR先暂时挂起吧，效状会给一个models管理的例子，可能会需要自己按照文件夹管理，等他给大家打个样，然后改一下

2023-09-14 08:53 UTC, WangXuhongCN requested changes

2023-09-14 08:53 UTC, WangXuhongCN commented on dashboard/biz_routers/eval_model.py
> +    model_info = {
这里的model_info会直接存在数据库里，不用你来写”根据endpoint地址去获取model的信息“的流程，你只需要写个通过ORM读数据库的功能就行了

2023-09-14 08:53 UTC, WangXuhongCN commented on dashboard/widgets/displays.py
>                  "record_file": ["书生·浦语 1.3.0", "送评模型1 1.0", "送评模型1 1.4"],
这里能否不要写死，还是要保留拓展性

2023-09-14 08:55 UTC, Echo-minn commented on dashboard/widgets/displays.py
>                  "record_file": ["书生·浦语 1.3.0", "送评模型1 1.0", "送评模型1 1.4"],
> 这里能否不要写死，还是要保留拓展性

因为我本地没有这个数据，所以我写死了，后续跟model_detail一样都是查询来的

2023-09-14 08:57 UTC, Echo-minn commented on dashboard/biz_routers/eval_model.py
> +    model_info = {
> 这里的model_info会直接存在数据库里，不用你来写”根据endpoint地址去获取model的信息“的流程，你只需要写个通过ORM读数据库的功能就行了

但是这里存到数据库里的数据不全，只有endpoint、AK和SK三个字段，其他字段信息不需要通过获取吗

2023-09-14 12:00 UTC, WangXuhongCN commented on dashboard/biz_routers/eval_model.py
> +    model_info = {
https://github.com/last-lab/last/blob/cdd68d5940abd64a6f3b98b06e200d19cb5a6a70/tests/test_pipeline.py#L27C5-L28C99
可以看上面的例子，我只需要endpoint、AK和SK三个主要的字段，以及一个type字段，就可以完整地新建一个LLM model，里面会有详细的modelinfo。我可以给你留一个接口，返回一个LLM类，你直接读我的LLM类里面的信息就行

2023-09-14 12:02 UTC, WangXuhongCN commented on dashboard/widgets/displays.py
>                  "record_file": ["书生·浦语 1.3.0", "送评模型1 1.0", "送评模型1 1.4"],
这里两种处理方式吧，一个是留TODO，另一个是留一个mock接口，后者可能更合理一些

2023-09-15 02:59 UTC, Echo-minn commented
> 这个PR先暂时挂起吧，效状会给一个models管理的例子，可能会需要自己按照文件夹管理，等他给大家打个样，然后改一下

biz_modles已修改

2023-09-15 03:00 UTC, Echo-minn commented on dashboard/biz_routers/eval_model.py
> +    model_info = {
TODO已添加

2023-09-15 03:00 UTC, Echo-minn commented on dashboard/widgets/displays.py
>                  "record_file": ["书生·浦语 1.3.0", "送评模型1 1.0", "送评模型1 1.4"],
TODO 已添加

2023-09-15 03:05 UTC, WangXuhongCN commented on dashboard/biz_routers/eval_model.py
> +    # TODO: @wangxuhong 这里需要将下面的 model_info 替换成 LLM 的信息
```suggestion
    # TODO: @wangxuhong 写一个接口，输入是endpoint, AK, SK. 
    输出是一个LLM类 类的定义 from last.types.llm import LLM
```

2023-09-15 03:10 UTC, WangXuhongCN approved these changes
LGTM

2023-09-15 03:14 UTC, merged