Feat dataset model stream
last-lab/last pull request #32
Opened 2023-09-14 09:06 UTC by AndyFAN1996

对齐评测集的数据结构

2023-09-14 09:17 UTC, WangXuhongCN requested changes

2023-09-14 09:17 UTC, WangXuhongCN commented on dashboard/biz_routers/dataset.py
> +@router.post("/dataset/json")
这里不建议使用mock了，可以调用services里面的file_upload.py上传真实文件

2023-09-15 06:55 UTC, Echo-minn approved these changes
LGTM

2023-09-18 01:50 UTC, WangXuhongCN approved these changes
LGTM

2023-09-18 03:22 UTC, closed without merging