Feat/annotation
last-lab/last pull request #39
Opened 2023-09-15 09:19 UTC by eveyuyi

更新 annotation 中的task、数据、annotation数据的存储数据格式定义

2023-09-18 03:25 UTC, WanChengXue requested changes

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation.py
> +    annotation_task_id: str  # 任务ID
这个annotation_task_id改成annotation_data_id，变量名进行统一

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation_dataset.py
> +    annotated_data_id: str # 标注对象的数据ID
有了annotation_task_id为什么要annotated_data_id?如果是数据集，你这个变量名应该变成一个dataset

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation_dataset.py
> +    anotated_data_type: str  # 标注对象的数据类型，text, image, video
标注task中哪有数据类型？一个数据集应该会有多种数据类型吧

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation_dataset.py
> +    state: StateCode
任务状态和annotation_task_type是不是重叠了？

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation_dataset.py
> +    annotation_target: str  # 标注的目的，sentiment, answer
这个字段是有必要的吗？

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation_dataset.py
> +    label_contents: List[Dict]  # 标注需要的label内容
需要有label内容吗？一旦确定好了是那种标注方式，label应该自动被载入了

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation.py
>      start: Optional[int] = None  # 起始位置，可选
这个类不要就删掉

2023-09-18 03:25 UTC, WanChengXue commented on last/types/annotation_dataset.py
> +    annotation_task_id: str  # 任务ID
为什么要有数据集的标注结果这个类？

2023-09-18 03:26 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    annotated_data_id: str # 标注对象的数据ID
是关联 被标注的数据 的数据库用的。

2023-09-18 03:27 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    anotated_data_type: str  # 标注对象的数据类型，text, image, video
这里是以每个标注任务为单位的数据定义，相当于每条数据。所以只有一种数据类型吧

2023-09-18 03:30 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    state: StateCode
不是的。state是“任务的完成状态”。annotation_task_type 是“ # 数据标注、审计标注”这个type

2023-09-18 03:31 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    annotation_target: str  # 标注的目的，sentiment, answer
label studio的字段，也许在之后模型训练阶段会用到。先改为optional好了。

2023-09-18 03:32 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    annotation_task_id: str  # 任务ID
用于存储结果啊

2023-09-18 03:32 UTC, eveyuyi commented on last/types/annotation.py
>      start: Optional[int] = None  # 起始位置，可选
给你参考用的，不需要就删了吧

2023-09-18 03:34 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    label_contents: List[Dict]  # 标注需要的label内容
okk 那先删了

2023-09-18 06:51 UTC, eveyuyi commented on last/types/annotation.py
> +    annotation_task_id: str  # 任务ID
okk

2023-09-18 07:45 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    anotated_data_type: str  # 标注对象的数据类型，text, image, video
已经修改为整个数据集，并修改对应字段

2023-09-18 07:51 UTC, eveyuyi commented on last/types/annotation_dataset.py
> +    state: StateCode
避免混淆，改成 annotation_method好了

2023-09-19 09:42 UTC, WanChengXue approved these changes
LGTM

2023-09-19 09:43 UTC, merged