Feat sso
last-lab/last pull request #48
Opened 2023-09-19 02:15 UTC by alvin6233

* 接入SSO统一登录
   验证需配置环境变量：SSO_CLIENT_ID & SSO_CLIENT_SECRET

2023-09-19 08:12 UTC, WangXuhongCN requested changes
有点小问题，期望回复一下

2023-09-19 08:12 UTC, WangXuhongCN commented on dashboard/settings.py
> +GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "dda88f31fc2eb97c8dab86a43b67aca3f7eb7d69")
这个是什么东西？明文写在这里，是不是不太好

2023-09-19 08:12 UTC, WangXuhongCN commented on dashboard/settings.py
> +    "SSO_REDIRECT_URL", "http://127.0.0.1:8000/admin/oauth2/sso_oauth2_provider"
这个SSO的服务是部署在local的吗？是不是未来要把这个东西接到真正的SSO服务器上？

2023-09-19 13:04 UTC, alvin6233 commented
> 有点小问题，期望回复一下

测试的参数，已经删除了

2023-09-20 01:45 UTC, WangXuhongCN commented
目前我尝试试用SSO登陆，登陆了之后不能跳转回原来的系统，这个PR是还没完成吗？

2023-09-20 01:50 UTC, WangXuhongCN commented
另外，因为你引入了Crypto这个新包，可能需要重新生成一下poetry.lock，然后将修改合并进来

2023-09-20 02:02 UTC, alvin6233 commented
> 目前我尝试试用SSO登陆，登陆了之后不能跳转回原来的系统，这个PR是还没完成吗？

需要配置CLIENT参数，为了安全可以单独向我要相关参数

2023-09-20 02:25 UTC, alvin6233 commented
> 另外，因为你引入了Crypto这个新包，可能需要重新生成一下poetry.lock，然后将修改合并进来

Done

2023-09-20 08:43 UTC, WangXuhongCN approved these changes

2023-09-20 08:43 UTC, merged