Feat new risk
last-lab/last pull request #58
Opened 2023-09-25 10:25 UTC by AndyFAN1996

1.二级和三级风险维度详情

2023-09-25 11:11 UTC, WangXuhongCN requested changes

2023-09-25 11:11 UTC, WangXuhongCN commented on dashboard/mock_data/mock_risk.py
> -
这里不建议删除，还是留着数据保护这个一级维度吧，测试用

2023-09-26 01:54 UTC, AndyFAN1996 commented on dashboard/mock_data/mock_risk.py
> -
done

2023-09-26 07:29 UTC, WangXuhongCN approved these changes

2023-09-26 07:32 UTC, merged